#!/bin/bash

command=$1

if [ "$command" = "start" ]; then
    echo "Starting shairport..."
    tmux new-session -d -s shairport
    tmux split-window -h -t shairport 'cd ~/Apps/shairport;perl shairport.pl'
    tmux select-pane -R -t shairport
    echo "Done."
elif [ "$command" = "stop" ]; then
    echo "Stopping shairport..."
    tmux kill-session -t shairport
    echo "Done. Goodbye!"
elif [ "$command" = "status" ]; then
    tmux ls | grep shairport
else
    echo "COMMANDS"
    echo "start - starts the shairport service"
    echo "stop - stops the shairport service"
    echo "status - shows the status of the shairport session"
fi 

