#!/bin/bash

session_name=$1

tmux new-session -d -s $session_name
tmux new-window -n consoles -t $session_name
tmux new-window -n tests -t $session_name 
tmux new-window -n server -t $session_name
tmux select-window -t $session_name:0
tmux attach -t $session_name
